/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.45.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as analytics from "../analytics.js";
import type * as forms from "../forms.js";
import type * as projects from "../projects.js";

declare const fullApi: ApiFromModules<{
  analytics: typeof analytics;
  forms: typeof forms;
  projects: typeof projects;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
