/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.45.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as analytics from "../analytics.js";
import type * as apiKeys from "../apiKeys.js";
import type * as audit from "../audit.js";
import type * as auth from "../auth.js";
import type * as forms from "../forms.js";
import type * as organizations from "../organizations.js";
import type * as projects from "../projects.js";
import type * as submissions from "../submissions.js";
import type * as users from "../users.js";
import type * as webhooks from "../webhooks.js";

declare const fullApi: ApiFromModules<{
  analytics: typeof analytics;
  apiKeys: typeof apiKeys;
  audit: typeof audit;
  auth: typeof auth;
  forms: typeof forms;
  organizations: typeof organizations;
  projects: typeof projects;
  submissions: typeof submissions;
  users: typeof users;
  webhooks: typeof webhooks;
}>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
